version: '3'
services:
# ####### Nginx
  nginx:
    image: nginx:stable-alpine
    restart: always
    ports:
        - 80:80
    volumes:
        - ./docker-data/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

# ####### MongoDB
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_LOGIN
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    ports:
      - $MONGO_PORT:27017
    volumes:
      - ./docker-data/mongo-data:/data/db

####### RabbitMQ
  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    container_name: rabbitmq
    restart: always
    volumes:
      - ./docker-data/rabbitmq/data/:/var/lib/rabbitmq/
      - ./docker-data/rabbitmq/logs/:/var/log/rabbitmq/
    ports:
      - 5672:5672
      - 15672:15672

####### Docs Service

  docs-service:
    build: ./docs-microservice
    restart: always

  
####### Auth Service

  auth-service:
    build: ./auth-microservice
    restart: always
    depends_on:
      - mongo
      - rabbitmq


####### Users Service

  users-service:
    build: ./users-microservice
    restart: always
    depends_on:
      - mongo
      - rabbitmq

####### Products Service
